global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "anbu-health-ai-api"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - "anbu-health-ai.kindrock-2ca528ff.centralindia.azurecontainerapps.io"
        labels:
          product: "anbu-health-ai"
          env: "production"
